export const ASSET_IMAGES = [
	'/assets/4 PAX.jpg',
	'/assets/7 PAX.jpg',
	'/assets/BOOTH AND PHONE POD.jpg',
	'/assets/BOOTH.jpg',
	'/assets/FOCUS RM 01.jpg',
	'/assets/FOCUS RM 02.jpg',
	'/assets/HYDRATION.jpg',
	'/assets/LOUNGE 01.jpg',
	'/assets/LOUNGE 02.jpg',
	'/assets/MK 01.jpg',
	'/assets/OP LOUNGE 01.jpg',
	'/assets/OP LOUNGE 02.jpg',
	'/assets/OP LOUNGE.jpg',
	'/assets/OP MK 01.jpg',
	'/assets/OP MK 02.jpg',
	'/assets/OP MK PANTRY.jpg',
	'/assets/P PAX.jpg',
	'/assets/PANTRY.jpg',
	'/assets/PROJECT ROOM 01.jpg',
	'/assets/PROJECT ROOM 02.jpg',
	'/assets/PROJECT ROOM 03.jpg',
	'/assets/PROJECT ROOM 04.jpg',
	'/assets/REPRO.jpg',
	'/assets/TRAINING RM 01.jpg',
	'/assets/TRAINING RM.jpg',
	'/assets/WS 01.jpg',
	'/assets/WS 02.jpg',
	'/assets/WS AND BOOTH.jpg'
];
